apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeebe-deployment
  labels:
    app: zeebe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeebe
  template:
    metadata:
      labels:
        app: zeebe
    spec:
      containers:
        - name: zeebe
          image: camunda/zeebe:8.4.1
          ports:
            - containerPort: 26500
            - containerPort: 9600
          env:
            - name: ZEEBE_LOG_LEVEL
              value: "debug"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"